In [3]:
#setup the environment variables

%matplotlib inline
import torch
import numpy as np

In [9]:
#initialize the tensor from directly data
data = [[1,1], [3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 1],
        [3, 4]])


From a NumPy <br>
Tensors can be created from NumPy array and vice versa.

In [10]:
#initialize from Numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

print(f"Numpy np)array value: \n {np_array} \n")
print(f"Tesor x_np value: \n {x_np} \n")

np.multiply(np_array, 2, out = np_array)

print(f"Numpy np_array after *2 operation: \n {np_array} \n")
print(f"Tesor x_np value after modifying numpy array: \n {x_np} \n")


Numpy np)array value: 
 [[1 1]
 [3 4]] 

Tesor x_np value: 
 tensor([[1, 1],
        [3, 4]], dtype=torch.int32) 

Numpy np_array after *2 operation: 
 [[2 2]
 [6 8]] 

Tesor x_np value after modifying numpy array: 
 tensor([[2, 2],
        [6, 8]], dtype=torch.int32) 



From another tensor: <br>
The new tensor retains the properties (shape, data type) of the argument tensor, unless explicitly overridden.

In [11]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3181, 0.2139],
        [0.7289, 0.3564]]) 



With random and constant values: <br>
"shape" is a tuple of tensor dimensions. Shape shows the number of rows and columns in the tensor. eg. shape = (#of rows, #of columns)

In [13]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.5377, 0.3152, 0.4558],
        [0.0901, 0.0229, 0.1640]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


Attributes of a Tensor <br>
Tensor attributes describe their shape, data type and the device on which they are stored.

In [16]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Tensor in GPU

In [18]:
# we move our tensor to the GPU if available

if torch.cuda.is_available():
    tensor = tensor.to('cuda')

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


Standard numpy-like indexing and slicing:

In [24]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Joining tensors<br>
You can use torch.cat to concatenate a sequence of tensors along a given dimension. torch.stack is another tensor joining option that is subtly different from torch.cat.

In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


Arithmetic Operations

In [28]:
# This computes the matrix multiplication between two tensors. y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
torch.matmul(tensor, tensor.T, out=y3)


# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [29]:
#In-place operations
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [30]:
#Bridge with NumPy

t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [31]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [32]:
n = np.ones(5)
t = torch.from_numpy(n)

In [33]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
